import React from "react";
import coinImage from "../assets/coins-image.jpg";
const LiveTraning = () => {
  return (
    <>
      <div className="live-traning-bg pb-4 mt-md-0 mt-3">
        <div className="container py-4 ">
          <h1 className="text-center text-white  fw-bolder">
            Live,personal training on any <br className="d-md-block d-d-none" />{" "}
            subject matter
          </h1>
          <p className="live-small-text   text-white text-center ">
            Full training in approximattely 50 training sessions. Topics coverd
            includes:
          </p>
          <div></div>

          {/* cards of information */}
          <div className="row">
            <div className="col-md-6 mb-4">
              <div className="d-flex  flex-column gap-4 live-training-cards">
                <div className="p-3 py-4 bg-white rounded-2">
                  <div className="mb-2">
                    <i className="fs-1  text-custom fw-bolder fa-solid fa-sack-dollar" />
                  </div>
                  <h6>
                    Gold,SBLC's,Diamonds,Fuel ,Historical Assets,Monetization
                    pof instruments,Crypto,Etc.
                  </h6>
                </div>
                <div className="p-3 py-4 bg-white rounded-2">
                  <div className="mb-2">
                    <i className="fs-1  text-custom fw-bolder fa-solid fa-headphones-simple" />
                  </div>
                  <h6>
                    Broker Call Sessoin:Ideas,Tips,and Q/Q with other brokers as
                    needed for hte owner.become a Mandate,Etc
                  </h6>
                </div>
                <div className="p-3 py-4 bg-white rounded-2">
                  <div className="mb-2">
                    <i className=" fs-1 text-custom fw-bolder fa-solid fa-chart-simple" />
                  </div>
                  <h6>
                    Personal training including all new features with marketing
                    industry tips ,guidelines ,improved processes,etc.
                  </h6>
                </div>
              </div>
            </div>
            <div className="col-md-6">
              <div className="d-flex  flex-column live-training-cards gap-4 ">
                <div className="p-3 py-4 bg-white rounded-2">
                  <div className="mb-2 ">
                    <div className="rotate-up d-inline-block">
                      <i className="  text-custom fw-bolder fa-solid fa-bullhorn fs-1" />
                    </div>
                  </div>
                  <h6>
                    Marketing tips and tricks of the trade ,etc .General and
                    detailed marketing -Over 50 Sessions,Quizzes,1:1 Training
                    ,Lead Processing Hands on Training!
                  </h6>
                </div>
                <div className="p-3 py-4 bg-white rounded-2">
                  <div className="mb-2">
                    {" "}
                    <i className="fs-1  text-custom fw-bolder fa-regular fa-clipboard" />
                  </div>
                  <h6>
                    Real Contacts training ,required documents for success.
                  </h6>
                </div>
                <div
                  className="p-3 py-4 bg-white rounded-2 d-flex 
                justify-content-center
                  flex-column gap-2 "
                >
                  <div className="live-traning-card ">
                    <i className="fa fa-check  rounded-circle p-1 small "></i>{" "}
                    You can start while training -a site is not required to
                    start .No License is Req!
                  </div>
                  <div className="live-traning-card ">
                    <i className="fa fa-check  rounded-circle p-1 small "></i>{" "}
                    Commission is Build-in into any contract in our business by
                    law!
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* owner Licence row */}

      <div className="container mt-md-0  py-md-5 py-2">
        <div className="row mb-3">
          {" "}
          <div className="col-md-6 col-12 my-4  pe-md-5  ">
            <div className="pe-md-5">
              <h1 className="fw-bolder">Owner License</h1>
              <div className=" border-b my-2"></div>
              <p>
                Run Your own business- while using live quality leads/offers
                generated by our global trade finance network!
              </p>
              <h1 className="fw-bolder">Payment/License Fee</h1>

              <div className=" border-b my-2"></div>
              <p>
                TFD Ultimate Lifetime License: $PLEASE INQUIRE.One time fee +
                Royalty.Include Full .Training (over 50 lectures w hands on
                contract training and live training - Become an expert
                consultant and a trusted facilitator for the largest
                transactions in the planet and in Global Trade Buy/Sell -what
                others learn only in 10 years!) , 50 +Leads/Contracts per week
                ,your own Trade Buy/Sell Network which will generate your own
                fresh new leads at no time !.(Lifetime License including all
                upgrades & Fee integration.)Also including 1 month of free
                Business Management of your account including all email/Phone
                calls w deal closing under your business!
              </p>
              <p className="small">
                **Optional Service:"Manage My Business" no Work is needed! WE DO
                IT ALL ! KEEP YOUR DAY JOB WHILE TRANSITION INTO THIS INCREDIBLE
                BUSINESS. it includes At LEAST 50+ Leads/Contracts/offers per
                Week and your own Global Trade Network.We fully manage your
                business including all daily emails,phons calls,Leads
                broadcast,and marketing of your offers for an incredibly low
                monthly labor cost. $Plase Inquiry/Monthly.
              </p>
            </div>
          </div>
          <div className="col-md-6 col-12">
            <img
              src={coinImage}
              alt="coinImage"
              className="img-fluid h-100 w-00"
            />
          </div>
        </div>
      </div>

      {/* owner Licence row */}
    </>
  );
};

export default LiveTraning;
